apiVersion: v1
kind: Secret
metadata:
  name: github-basic-auth
  annotations:
    tekton.dev/git-0: http://gitea-gitea.apps.df-apiops.2enh.p1.openshiftapps.com
type: kubernetes.io/basic-auth
stringData:
  username: gitea
  password: openshift