---
# tasks to create a konnect dataplane
- name: Authenticate to Konnect
  ansible.builtin.uri:
    url: "https://{{ base_url }}/kauth/api/v1/authenticate"
    method: POST
    body_format: json
    body: '{ "username": "{{ konnect_email }}", "password":"{{ konnect_pass }}" }'
    return_content: yes
  register: login
  vars:
    base_url: "cloud.konghq.com"

- name: login output response
  debug: 
    var: login

- name: "Create Konnect {{ runtime_group }} Runtime group"
  include_tasks: konnect-runtime-group.yaml

- name: "Create Konnect Cert - {{ runtime_group }} Runtime Group"
  include_tasks: konnect-cert.yaml

- name: "Deploy Konnect Dataplanes -  {{ runtime_group }} Runtime Group"
  include_tasks: konnect-helm-dp.yaml

- name: "Deck Configure Konnect Runtime Group - {{ runtime_group }}"
  include_tasks: konnect-runtime-group-configure.yaml
