---
# tasks to create a konnect dataplane
- name: Authenticate to Konnect
  ansible.builtin.uri:
    url: "https://{{ base_url }}/kauth/api/v1/authenticate"
    method: POST
    body_format: json
    body: '{ "username": "{{ konnect_email }}", "password":"{{ konnect_pass }}" }'
    return_content: yes
  register: login
  vars:
    base_url: "cloud.konghq.com"

- name: login output response
  debug: 
    var: login

- name: Create Konnect Gateway Namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ namespace }}"
    state: present
    
- name: "Create Konnect {{ runtime_group }} Runtime group"
  include_tasks: konnect-runtime-group.yaml

- name: "Create Konnect Cert - {{ runtime_group }} Runtime Group"
  include_tasks: konnect-cert.yaml

- name: "Deploy Konnect Dataplanes -  {{ runtime_group }} Runtime Group"
  include_tasks: konnect-helm-dp.yaml

- name: "Deck Configure Konnect Runtime Group - {{ runtime_group }}"
  include_tasks: konnect-runtime-group-configure.yaml

- name: "Get Konnect - Kuberentes SVC/Loadbalancers"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    namespace: "{{ namespace }}"
    name: "{{ dataplane_name }}-kong-proxy"
  register: dp_svc

- name: Create kong_proxy fact
  ansible.builtin.set_fact:
    kong_proxy: "{{ dp_svc.resources[0].status.loadBalancer.ingress[0].hostname }}"

- name: Append kong_proxy fact to demo_fact dictionary
  ansible.builtin.set_fact:
    demo_facts: "{{ demo_facts | combine({namespace: kong_proxy}) }}"

- name: Append Insomnia Konnect Factos to demo_fact dictionary
  ansible.builtin.set_fact:
    demo_facts: "{{ demo_facts | combine({ namespace: {'scheme': 'http', 'base_path': '', 'host': kong_proxy,'apikey': 'konnect', 'id': '0'}}) }}"
