apiVersion: v1
kind: ConfigMap
metadata:
  name: deck-{{runtime_group}}-rg
data:
  deck.yaml: |
    _format_version: "3.0"
    _konnect:
      runtime_group_name: {{runtime_group}}
    consumers:
    - custom_id: jane
      keyauth_credentials:
      - key: konnect
        tags:
        - global
      tags:
      - global
      username: jane
    plugins:
    - config:
        day: null
        error_code: 429
        error_message: API rate limit exceeded
        fault_tolerant: true
        header_name: null
        hide_client_headers: false
        hour: null
        limit_by: consumer
        minute: 5
        month: null
        path: null
        policy: local
        redis_database: 0
        redis_host: null
        redis_password: null
        redis_port: 6379
        redis_server_name: null
        redis_ssl: false
        redis_ssl_verify: false
        redis_timeout: 2000
        redis_username: null
        second: null
        year: null
      enabled: true
      name: rate-limiting
      protocols:
      - grpc
      - grpcs
      - http
      - https
      tags:
      - global
    - config:
        credentials: false
        exposed_headers: null
        headers: null
        max_age: null
        methods:
        - GET
        - HEAD
        - PUT
        - PATCH
        - POST
        - DELETE
        - OPTIONS
        - TRACE
        - CONNECT
        origins: null
        preflight_continue: false
      enabled: true
      name: cors
      protocols:
      - grpc
      - grpcs
      - http
      - https