apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: init-konnect-runtimegroups-{{ runtime_group }}-
spec:
  taskRef:
    name: deck-cli
  workspaces: 
    - name: source 
      configMap:
        name: deck-{{ runtime_group }}-rg
    - name: deck
      secret:
        secretName: deck
  params: 
    - name: SCRIPT
      value: |
        #!/usr/bin/env sh
        deck sync --select-tag global --state deck.yaml --konnect-runtime-group-name {{ runtime_group }}

