
---
- name: 'Install Kong APISecOps Demo'
  hosts: localhost
  connection: local
  vars: 
    # list of konnect dataplanes and respective runtime groups that will be created 
    konnect: 
      - runtime_group: default
        namespace: kong-sandbox
        crt_secret: konnect-sandbox-crt
        pipeline_namespace: apiops-gateway
      - runtime_group: dev
        namespace: kong-dev
        crt_secret: konnect-dev-crt
        pipeline_namespace: apiops-gateway

    # list of apiops namespaces and respective tekton pipelines needed in each namespace
    apiops: 
      - namespace: disputes-apispec
        pipelines: 
          - disputes-apispec-review-pipeline.yaml
      - namespace: apiops-gateway
        pipelines: 
          - apiops-sandbox-pipeline.yaml
          - apiops-dev-pipeline.yaml

    # list of pipelines runs that need to be created and placed into sub-dir run
    pipeline_runs:
      - disputes-pipeline-run
      - apiops-sandbox-pipeline-run
      - apiops-dev-pipeline-run
    
    # list of kuberentes microservices that need to be deployed, name of namespace to be created, and path to kuberentes manifest
    microservices: 
      - namespace: disputes-dev
        manifest_path: "{{ playbook_dir}}/disputes/disputes.yaml"

  tasks: 
# Operators Cert Manager and Openshift Pipelines
    - name: Create Konnect Runtime Groups and Dataplanes
      include_tasks: tasks/operator/tasks-operator.yaml

# # Gitea
    - name: Create Konnect Runtime Groups and Dataplanes
      include_tasks: tasks/gitea/tasks-gitea.yaml

# #APIOps 
    - name: Create and Configure APIOps Namespace
      include_tasks: tasks/tekton/tasks-tekton.yaml
      vars: 
        namespace: "{{ item.namespace }}"
        pipelines: "{{ item.pipelines }}"
        gitea_domain: "{{ gitea_route.spec.host }}"
        gitea_namespace: gitea
      loop: "{{ apiops }}"
            
    - name: Create PipelineRuns 
      ansible.builtin.template: 
        src: "tasks/tekton/templates/pipeline-run/{{ item }}.j2"
        dest: "../run/{{ item }}.yaml"
      vars: 
        github_domain: "{{ gitea_route.spec.host }}"
        protocol: http
      loop: "{{ pipeline_runs }}"

  # Konnect
    - name: Create Konnect Runtime Groups and Dataplanes
      include_tasks: tasks/konnect/tasks-konnect.yaml
      vars: 
        runtime_group: "{{ item.runtime_group }}"
        namespace: "{{ item.namespace }}"
        crt_secret: "{{ item.crt_secret }}"
        pipeline_namespace: "{{ item.pipeline_namespace }}"
      loop: "{{ konnect }}"
  
  # Disputes Microservice
    - name: Create Konnect Runtime Groups and Dataplanes
      include_tasks: tasks/microservice/tasks-microservice.yaml
      vars: 
        namespace: "{{ item.namespace }}"
        manifest_path: "{{ item.manifest_path }}"
      loop: "{{ microservices }}"

