apiVersion: v1
kind: Secret
metadata:
  name: github-basic-auth
  annotations:
    tekton.dev/git-0: http://{{ github_domain }}
type: kubernetes.io/basic-auth
stringData:
  username: gitea
  password: openshift
---
apiVersion: v1
kind: Secret
metadata:
  name: deck
type: Opaque
stringData:
  .deck.yaml: |-
    konnect-email: {{ konnect_email }}
    konnect-password: {{ konnect_pass }}