apiVersion: v1
kind: Secret
metadata:
  name: github-basic-auth
  annotations:
    tekton.dev/git-0: {{ protocol }}://{{ github_domain }}
type: kubernetes.io/basic-auth
stringData:
  username: gitea
  password: openshift
---
apiVersion: v1
kind: Secret
metadata:
  name: deck
type: Opaque
stringData:
  .deck.yaml: |-
    konnect-token: {{ konnect_pat }}
